version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: codesathi-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: codesathidb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codesathi-backend
    restart: always
    ports:
      - "4010:4010"
    environment:
      - DATABASE_URL=postgresql://admin:adminpassword@db:5432/codesathidb?schema=public
      - JWT_SECRET=supersecretjwtkey_change_in_prod
      - PORT=4010
      - NODE_ENV=production
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  pgdata:
