// ===== HACKTEAM MOCK DATA STORE =====

const AVATAR_COLORS = [
  'linear-gradient(135deg, #00d4ff, #0080ff)',
  'linear-gradient(135deg, #a855f7, #6d28d9)',
  'linear-gradient(135deg, #00ff88, #00b865)',
  'linear-gradient(135deg, #f472b6, #ec4899)',
  'linear-gradient(135deg, #fb923c, #f97316)',
  'linear-gradient(135deg, #facc15, #eab308)',
  'linear-gradient(135deg, #00d4ff, #a855f7)',
  'linear-gradient(135deg, #ef4444, #dc2626)',
];

const SKILL_TAGS = [
  { name: 'React', color: 'blue' },
  { name: 'Python', color: 'green' },
  { name: 'Machine Learning', color: 'purple' },
  { name: 'UI/UX', color: 'pink' },
  { name: 'Node.js', color: 'green' },
  { name: 'Blockchain', color: 'orange' },
  { name: 'Flutter', color: 'blue' },
  { name: 'TypeScript', color: 'blue' },
  { name: 'Rust', color: 'orange' },
  { name: 'Go', color: 'blue' },
  { name: 'AWS', color: 'yellow' },
  { name: 'Figma', color: 'pink' },
  { name: 'Docker', color: 'blue' },
  { name: 'GraphQL', color: 'purple' },
  { name: 'TensorFlow', color: 'orange' },
  { name: 'Solidity', color: 'purple' },
  { name: 'Swift', color: 'orange' },
  { name: 'Next.js', color: 'blue' },
  { name: 'Firebase', color: 'yellow' },
  { name: 'PostgreSQL', color: 'blue' },
  { name: 'DevOps', color: 'green' },
  { name: 'NLP', color: 'purple' },
  { name: 'Computer Vision', color: 'green' },
  { name: 'Web3', color: 'purple' },
  { name: 'Kotlin', color: 'orange' },
  { name: 'Vue.js', color: 'green' },
  { name: 'Cybersecurity', color: 'red' },
  { name: 'Data Science', color: 'blue' },
  { name: 'AR/VR', color: 'pink' },
  { name: 'IoT', color: 'green' },
];

const ROLES = ['Builder', 'Designer', 'PM', 'Domain Expert'];
const EXPERIENCE_LEVELS = ['Beginner', 'Intermediate', 'Advanced'];
const TIMEZONES = ['UTC-8 (PST)', 'UTC-5 (EST)', 'UTC+0 (GMT)', 'UTC+1 (CET)', 'UTC+5:30 (IST)', 'UTC+8 (CST)', 'UTC+9 (JST)', 'UTC+10 (AEST)'];

const USERS = [
  {
    id: 1,
    name: 'Aisha Patel',
    initials: 'AP',
    bio: 'Full-stack developer passionate about building scalable web apps. Love hackathons!',
    skills: ['React', 'Node.js', 'TypeScript'],
    experience: 'Advanced',
    timezone: 'UTC+5:30 (IST)',
    role: 'Builder',
    github: 'github.com/aishap',
    linkedin: 'linkedin.com/in/aishap',
    openToTeam: true,
    avatarColor: 0,
    hackathonsAttended: 12,
    teamsFormed: 8,
    projectsBuilt: 6,
  },
  {
    id: 2,
    name: 'Marcus Chen',
    initials: 'MC',
    bio: 'ML engineer & data enthusiast. Looking for creative teams to build AI-powered solutions.',
    skills: ['Python', 'Machine Learning', 'TensorFlow'],
    experience: 'Advanced',
    timezone: 'UTC-8 (PST)',
    role: 'Builder',
    github: 'github.com/marcusc',
    linkedin: 'linkedin.com/in/marcusc',
    openToTeam: true,
    avatarColor: 1,
    hackathonsAttended: 15,
    teamsFormed: 10,
    projectsBuilt: 9,
  },
  {
    id: 3,
    name: 'Sofia Rodriguez',
    initials: 'SR',
    bio: 'Product designer who turns ideas into beautiful, user-centric experiences.',
    skills: ['UI/UX', 'Figma', 'React'],
    experience: 'Intermediate',
    timezone: 'UTC-5 (EST)',
    role: 'Designer',
    github: 'github.com/sofiar',
    linkedin: 'linkedin.com/in/sofiar',
    openToTeam: true,
    avatarColor: 2,
    hackathonsAttended: 7,
    teamsFormed: 5,
    projectsBuilt: 4,
  },
  {
    id: 4,
    name: 'James Okonkwo',
    initials: 'JO',
    bio: 'Blockchain developer building the decentralized future. Web3 maximalist.',
    skills: ['Solidity', 'Web3', 'Rust'],
    experience: 'Advanced',
    timezone: 'UTC+0 (GMT)',
    role: 'Builder',
    github: 'github.com/jameso',
    linkedin: 'linkedin.com/in/jameso',
    openToTeam: false,
    avatarColor: 3,
    hackathonsAttended: 20,
    teamsFormed: 14,
    projectsBuilt: 11,
  },
  {
    id: 5,
    name: 'Yuki Tanaka',
    initials: 'YT',
    bio: 'Mobile dev specializing in cross-platform apps. Flutter evangelist.',
    skills: ['Flutter', 'Kotlin', 'Firebase'],
    experience: 'Intermediate',
    timezone: 'UTC+9 (JST)',
    role: 'Builder',
    github: 'github.com/yukit',
    linkedin: 'linkedin.com/in/yukit',
    openToTeam: true,
    avatarColor: 4,
    hackathonsAttended: 5,
    teamsFormed: 3,
    projectsBuilt: 3,
  },
  {
    id: 6,
    name: 'Elena Popova',
    initials: 'EP',
    bio: 'DevOps engineer who keeps things running. Passionate about cloud infrastructure and automation.',
    skills: ['AWS', 'Docker', 'DevOps'],
    experience: 'Advanced',
    timezone: 'UTC+1 (CET)',
    role: 'Builder',
    github: 'github.com/elenap',
    linkedin: 'linkedin.com/in/elenap',
    openToTeam: true,
    avatarColor: 5,
    hackathonsAttended: 9,
    teamsFormed: 6,
    projectsBuilt: 5,
  },
  {
    id: 7,
    name: 'David Kim',
    initials: 'DK',
    bio: 'Product manager turned hacker. I bridge the gap between tech and business.',
    skills: ['UI/UX', 'Data Science', 'Python'],
    experience: 'Intermediate',
    timezone: 'UTC-5 (EST)',
    role: 'PM',
    github: 'github.com/davidk',
    linkedin: 'linkedin.com/in/davidk',
    openToTeam: true,
    avatarColor: 6,
    hackathonsAttended: 6,
    teamsFormed: 4,
    projectsBuilt: 3,
  },
  {
    id: 8,
    name: 'Priya Sharma',
    initials: 'PS',
    bio: 'Computer vision researcher exploring the intersection of AI and healthcare.',
    skills: ['Computer Vision', 'Python', 'TensorFlow'],
    experience: 'Advanced',
    timezone: 'UTC+5:30 (IST)',
    role: 'Domain Expert',
    github: 'github.com/priyas',
    linkedin: 'linkedin.com/in/priyas',
    openToTeam: true,
    avatarColor: 7,
    hackathonsAttended: 8,
    teamsFormed: 5,
    projectsBuilt: 4,
  },
  {
    id: 9,
    name: 'Lucas Müller',
    initials: 'LM',
    bio: 'Backend engineer who loves APIs and distributed systems. Golang enthusiast.',
    skills: ['Go', 'PostgreSQL', 'Docker'],
    experience: 'Advanced',
    timezone: 'UTC+1 (CET)',
    role: 'Builder',
    github: 'github.com/lucasm',
    linkedin: 'linkedin.com/in/lucasm',
    openToTeam: false,
    avatarColor: 0,
    hackathonsAttended: 11,
    teamsFormed: 7,
    projectsBuilt: 6,
  },
  {
    id: 10,
    name: 'Amira Hassan',
    initials: 'AH',
    bio: 'NLP researcher fascinated by language models and conversational AI.',
    skills: ['NLP', 'Python', 'Machine Learning'],
    experience: 'Intermediate',
    timezone: 'UTC+0 (GMT)',
    role: 'Builder',
    github: 'github.com/amirah',
    linkedin: 'linkedin.com/in/amirah',
    openToTeam: true,
    avatarColor: 1,
    hackathonsAttended: 4,
    teamsFormed: 2,
    projectsBuilt: 2,
  },
  {
    id: 11,
    name: 'Ryan Brooks',
    initials: 'RB',
    bio: 'Cybersecurity specialist with a passion for making the internet safer.',
    skills: ['Cybersecurity', 'Python', 'DevOps'],
    experience: 'Advanced',
    timezone: 'UTC-8 (PST)',
    role: 'Domain Expert',
    github: 'github.com/ryanb',
    linkedin: 'linkedin.com/in/ryanb',
    openToTeam: true,
    avatarColor: 2,
    hackathonsAttended: 10,
    teamsFormed: 6,
    projectsBuilt: 5,
  },
  {
    id: 12,
    name: 'Mei Lin Wong',
    initials: 'MW',
    bio: 'Frontend developer and creative coder. I make things look and feel amazing.',
    skills: ['React', 'Next.js', 'UI/UX'],
    experience: 'Intermediate',
    timezone: 'UTC+8 (CST)',
    role: 'Designer',
    github: 'github.com/meilinw',
    linkedin: 'linkedin.com/in/meilinw',
    openToTeam: true,
    avatarColor: 3,
    hackathonsAttended: 6,
    teamsFormed: 4,
    projectsBuilt: 3,
  },
  {
    id: 13,
    name: 'Omar Al-Rashid',
    initials: 'OR',
    bio: 'IoT and embedded systems developer. Building the connected world.',
    skills: ['IoT', 'Python', 'AWS'],
    experience: 'Intermediate',
    timezone: 'UTC+0 (GMT)',
    role: 'Builder',
    github: 'github.com/omarr',
    linkedin: 'linkedin.com/in/omarr',
    openToTeam: true,
    avatarColor: 4,
    hackathonsAttended: 3,
    teamsFormed: 2,
    projectsBuilt: 1,
  },
  {
    id: 14,
    name: 'Chloe Bennett',
    initials: 'CB',
    bio: 'AR/VR enthusiast exploring immersive experiences. Unity and Unreal developer.',
    skills: ['AR/VR', 'UI/UX', 'Swift'],
    experience: 'Beginner',
    timezone: 'UTC-5 (EST)',
    role: 'Builder',
    github: 'github.com/chloeb',
    linkedin: 'linkedin.com/in/chloeb',
    openToTeam: true,
    avatarColor: 5,
    hackathonsAttended: 2,
    teamsFormed: 1,
    projectsBuilt: 1,
  },
  {
    id: 15,
    name: 'Arjun Nair',
    initials: 'AN',
    bio: 'Full-stack developer with a love for clean architecture and GraphQL.',
    skills: ['GraphQL', 'TypeScript', 'Next.js'],
    experience: 'Advanced',
    timezone: 'UTC+5:30 (IST)',
    role: 'Builder',
    github: 'github.com/arjunn',
    linkedin: 'linkedin.com/in/arjunn',
    openToTeam: true,
    avatarColor: 6,
    hackathonsAttended: 14,
    teamsFormed: 9,
    projectsBuilt: 7,
  },
  {
    id: 16,
    name: 'Isabella Costa',
    initials: 'IC',
    bio: 'Data scientist turning raw data into actionable insights. Kaggle competitor.',
    skills: ['Data Science', 'Python', 'Machine Learning'],
    experience: 'Intermediate',
    timezone: 'UTC-8 (PST)',
    role: 'Builder',
    github: 'github.com/isabellac',
    linkedin: 'linkedin.com/in/isabellac',
    openToTeam: false,
    avatarColor: 7,
    hackathonsAttended: 5,
    teamsFormed: 3,
    projectsBuilt: 2,
  },
  {
    id: 17,
    name: 'Ethan Wright',
    initials: 'EW',
    bio: 'Vue.js champion and open source contributor. Building tools developers love.',
    skills: ['Vue.js', 'TypeScript', 'Node.js'],
    experience: 'Advanced',
    timezone: 'UTC+10 (AEST)',
    role: 'Builder',
    github: 'github.com/ethanw',
    linkedin: 'linkedin.com/in/ethanw',
    openToTeam: true,
    avatarColor: 0,
    hackathonsAttended: 8,
    teamsFormed: 5,
    projectsBuilt: 4,
  },
  {
    id: 18,
    name: 'Zara Ahmed',
    initials: 'ZA',
    bio: 'Healthcare domain expert bridging medicine and technology.',
    skills: ['Python', 'Data Science', 'NLP'],
    experience: 'Intermediate',
    timezone: 'UTC+0 (GMT)',
    role: 'Domain Expert',
    github: 'github.com/zaraa',
    linkedin: 'linkedin.com/in/zaraa',
    openToTeam: true,
    avatarColor: 1,
    hackathonsAttended: 4,
    teamsFormed: 2,
    projectsBuilt: 2,
  },
  {
    id: 19,
    name: 'Leo Fischer',
    initials: 'LF',
    bio: 'Smart contract auditor and DeFi researcher. Making crypto safer.',
    skills: ['Solidity', 'Blockchain', 'Cybersecurity'],
    experience: 'Advanced',
    timezone: 'UTC+1 (CET)',
    role: 'Domain Expert',
    github: 'github.com/leof',
    linkedin: 'linkedin.com/in/leof',
    openToTeam: true,
    avatarColor: 2,
    hackathonsAttended: 13,
    teamsFormed: 9,
    projectsBuilt: 8,
  },
  {
    id: 20,
    name: 'Nina Kowalski',
    initials: 'NK',
    bio: 'UX researcher and interaction designer. I put users first, always.',
    skills: ['UI/UX', 'Figma', 'AR/VR'],
    experience: 'Beginner',
    timezone: 'UTC+1 (CET)',
    role: 'Designer',
    github: 'github.com/ninak',
    linkedin: 'linkedin.com/in/ninak',
    openToTeam: true,
    avatarColor: 3,
    hackathonsAttended: 2,
    teamsFormed: 1,
    projectsBuilt: 1,
  },
];

const HACKATHONS = [
  {
    id: 1,
    name: 'HackAI 2026',
    date: 'Mar 15–17, 2026',
    location: 'San Francisco, CA',
    online: false,
    prize: '$50,000',
    tags: ['AI', 'Machine Learning', 'NLP'],
    description: 'The premier AI hackathon bringing together the brightest minds in artificial intelligence. Build innovative AI solutions in 48 hours.',
    attendees: [1, 2, 8, 10, 16],
    bannerGradient: 'linear-gradient(135deg, #a855f7, #6d28d9)',
    website: 'https://hackai2026.dev',
    organizer: 'AI Foundation',
  },
  {
    id: 2,
    name: 'ETHGlobal Brussels',
    date: 'Apr 5–7, 2026',
    location: 'Brussels, Belgium',
    online: false,
    prize: '$100,000',
    tags: ['Web3', 'Blockchain', 'DeFi'],
    description: 'Build the decentralized future at ETHGlobal Brussels. Smart contracts, DeFi protocols, and more.',
    attendees: [4, 19, 6, 9],
    bannerGradient: 'linear-gradient(135deg, #00d4ff, #0080ff)',
    website: 'https://ethglobal.com/brussels',
    organizer: 'ETHGlobal',
  },
  {
    id: 3,
    name: 'HealthHack',
    date: 'Apr 20–22, 2026',
    location: 'Online',
    online: true,
    prize: '$25,000',
    tags: ['Health', 'AI', 'IoT'],
    description: 'Hack for a healthier world. Build solutions that improve healthcare delivery, patient outcomes, and medical research.',
    attendees: [8, 18, 13, 14, 3],
    bannerGradient: 'linear-gradient(135deg, #00ff88, #00b865)',
    website: 'https://healthhack.org',
    organizer: 'MedTech Alliance',
  },
  {
    id: 4,
    name: 'TreeHacks 2026',
    date: 'May 3–5, 2026',
    location: 'Stanford, CA',
    online: false,
    prize: '$75,000',
    tags: ['AI', 'Climate', 'Education'],
    description: 'Stanford\'s flagship hackathon. Build projects that create positive social impact.',
    attendees: [1, 2, 3, 7, 15],
    bannerGradient: 'linear-gradient(135deg, #fb923c, #f97316)',
    website: 'https://treehacks.com',
    organizer: 'Stanford ACM',
  },
  {
    id: 5,
    name: 'HackTheVerse',
    date: 'May 18–20, 2026',
    location: 'Online',
    online: true,
    prize: '$30,000',
    tags: ['AR/VR', 'Gaming', 'Web3'],
    description: 'Enter the metaverse. Build immersive experiences, games, and virtual worlds.',
    attendees: [14, 20, 12, 5],
    bannerGradient: 'linear-gradient(135deg, #f472b6, #ec4899)',
    website: 'https://hacktheverse.io',
    organizer: 'MetaVerse Labs',
  },
  {
    id: 6,
    name: 'DevSprint India',
    date: 'Jun 1–3, 2026',
    location: 'Bengaluru, India',
    online: false,
    prize: '₹20,00,000',
    tags: ['Full Stack', 'AI', 'Fintech'],
    description: 'India\'s largest hackathon for developers. Build production-ready apps in 48 hours.',
    attendees: [1, 8, 15, 18],
    bannerGradient: 'linear-gradient(135deg, #facc15, #eab308)',
    website: 'https://devsprint.in',
    organizer: 'DevSprint Foundation',
  },
  {
    id: 7,
    name: 'CyberShield CTF',
    date: 'Jun 15–16, 2026',
    location: 'Online',
    online: true,
    prize: '$15,000',
    tags: ['Cybersecurity', 'Networking', 'CTF'],
    description: 'Capture the flag competition combined with a hackathon. Build security tools and solve challenges.',
    attendees: [11, 19, 6, 9],
    bannerGradient: 'linear-gradient(135deg, #ef4444, #dc2626)',
    website: 'https://cybershieldctf.com',
    organizer: 'CyberShield',
  },
  {
    id: 8,
    name: 'ClimateHack',
    date: 'Jul 10–12, 2026',
    location: 'London, UK',
    online: false,
    prize: '£40,000',
    tags: ['Climate', 'IoT', 'Data Science'],
    description: 'Build technology solutions to combat climate change. Data-driven approaches to environmental challenges.',
    attendees: [13, 18, 6, 10, 7],
    bannerGradient: 'linear-gradient(135deg, #00ff88, #00d4ff)',
    website: 'https://climatehack.earth',
    organizer: 'Green Tech Alliance',
  },
];

const TEAM_POSTINGS = [
  {
    id: 1,
    hackathonId: 1,
    hackathonName: 'HackAI 2026',
    projectIdea: 'AI-powered mental health companion using NLP',
    rolesNeeded: ['Builder', 'Designer', 'Domain Expert'],
    currentSize: 2,
    maxSize: 4,
    creator: USERS[1],
    members: [USERS[1], USERS[9]],
  },
  {
    id: 2,
    hackathonId: 2,
    hackathonName: 'ETHGlobal Brussels',
    projectIdea: 'Decentralized identity verification for refugees',
    rolesNeeded: ['Builder', 'PM'],
    currentSize: 3,
    maxSize: 5,
    creator: USERS[3],
    members: [USERS[3], USERS[18], USERS[5]],
  },
  {
    id: 3,
    hackathonId: 3,
    hackathonName: 'HealthHack',
    projectIdea: 'Remote patient monitoring with IoT sensors',
    rolesNeeded: ['Builder', 'Designer'],
    currentSize: 2,
    maxSize: 4,
    creator: USERS[12],
    members: [USERS[12], USERS[17]],
  },
  {
    id: 4,
    hackathonId: 4,
    hackathonName: 'TreeHacks 2026',
    projectIdea: 'Gamified climate action tracker',
    rolesNeeded: ['Designer', 'Builder'],
    currentSize: 3,
    maxSize: 5,
    creator: USERS[2],
    members: [USERS[2], USERS[6], USERS[14]],
  },
  {
    id: 5,
    hackathonId: 1,
    hackathonName: 'HackAI 2026',
    projectIdea: null,
    rolesNeeded: ['Builder', 'Designer', 'PM'],
    currentSize: 1,
    maxSize: 4,
    creator: USERS[7],
    members: [USERS[7]],
  },
  {
    id: 6,
    hackathonId: 5,
    hackathonName: 'HackTheVerse',
    projectIdea: 'VR collaborative workspace for remote teams',
    rolesNeeded: ['Builder', 'Designer'],
    currentSize: 2,
    maxSize: 3,
    creator: USERS[13],
    members: [USERS[13], USERS[19]],
  },
  {
    id: 7,
    hackathonId: 6,
    hackathonName: 'DevSprint India',
    projectIdea: 'AI financial advisor for rural communities',
    rolesNeeded: ['Domain Expert', 'Designer'],
    currentSize: 2,
    maxSize: 4,
    creator: USERS[0],
    members: [USERS[0], USERS[14]],
  },
  {
    id: 8,
    hackathonId: 7,
    hackathonName: 'CyberShield CTF',
    projectIdea: 'Automated vulnerability scanner for open source',
    rolesNeeded: ['Builder'],
    currentSize: 3,
    maxSize: 4,
    creator: USERS[10],
    members: [USERS[10], USERS[18], USERS[8]],
  },
];

const SHOWCASE_PROJECTS = [
  {
    id: 1,
    name: 'MindBridge',
    hackathon: 'HackAI 2025',
    description: 'An AI-powered mental health companion that uses NLP to provide empathetic conversations and mood tracking.',
    team: [USERS[1], USERS[9], USERS[2]],
    techStack: ['Python', 'TensorFlow', 'React', 'Node.js'],
    link: 'https://devpost.com/mindbridge',
    placement: '🏆 1st Place',
    bannerGradient: 'linear-gradient(135deg, #a855f7, #00d4ff)',
  },
  {
    id: 2,
    name: 'ChainID',
    hackathon: 'ETHGlobal Paris 2025',
    description: 'Decentralized identity verification system for refugees using blockchain and zero-knowledge proofs.',
    team: [USERS[3], USERS[18], USERS[5]],
    techStack: ['Solidity', 'React', 'Node.js', 'Web3'],
    link: 'https://devpost.com/chainid',
    placement: '🥈 2nd Place',
    bannerGradient: 'linear-gradient(135deg, #00d4ff, #0080ff)',
  },
  {
    id: 3,
    name: 'VitalWatch',
    hackathon: 'HealthHack 2025',
    description: 'Remote patient monitoring platform using IoT sensors with real-time alerts for caregivers.',
    team: [USERS[12], USERS[17], USERS[7]],
    techStack: ['Python', 'IoT', 'React', 'Firebase'],
    link: 'https://devpost.com/vitalwatch',
    placement: '🏆 Best Health Innovation',
    bannerGradient: 'linear-gradient(135deg, #00ff88, #00b865)',
  },
  {
    id: 4,
    name: 'EcoQuest',
    hackathon: 'TreeHacks 2025',
    description: 'Gamified climate action tracker that rewards users for sustainable lifestyle choices.',
    team: [USERS[2], USERS[6], USERS[0]],
    techStack: ['Next.js', 'Python', 'PostgreSQL', 'Figma'],
    link: 'https://devpost.com/ecoquest',
    placement: null,
    bannerGradient: 'linear-gradient(135deg, #fb923c, #facc15)',
  },
  {
    id: 5,
    name: 'SecureScan',
    hackathon: 'CyberShield 2025',
    description: 'Automated open source vulnerability scanner with AI-powered threat classification.',
    team: [USERS[10], USERS[8], USERS[5]],
    techStack: ['Go', 'Python', 'Docker', 'Machine Learning'],
    link: 'https://devpost.com/securescan',
    placement: '🏆 1st Place',
    bannerGradient: 'linear-gradient(135deg, #ef4444, #a855f7)',
  },
  {
    id: 6,
    name: 'LinguaFlow',
    hackathon: 'HackAI 2025',
    description: 'Real-time language translation for video calls using advanced NLP and speech synthesis.',
    team: [USERS[9], USERS[1], USERS[14]],
    techStack: ['Python', 'NLP', 'React', 'WebRTC'],
    link: 'https://devpost.com/linguaflow',
    placement: '🥉 3rd Place',
    bannerGradient: 'linear-gradient(135deg, #f472b6, #a855f7)',
  },
];

const MESSAGES = [
  {
    id: 1,
    type: 'request',
    from: USERS[1],
    message: 'Hey! I saw you\'re into React and UI/UX. We\'re building an AI mental health app for HackAI 2026 and need a designer. Interested?',
    timestamp: '2 hours ago',
    status: 'pending',
  },
  {
    id: 2,
    type: 'request',
    from: USERS[3],
    message: 'Looking for a frontend dev for our Web3 identity project at ETHGlobal. Your React skills would be perfect!',
    timestamp: '5 hours ago',
    status: 'pending',
  },
  {
    id: 3,
    type: 'chat',
    from: USERS[2],
    messages: [
      { text: 'Hey Sofia! Excited to work together at TreeHacks!', sender: 'them', time: '10:30 AM' },
      { text: 'Me too! I\'ve been brainstorming some ideas.', sender: 'me', time: '10:32 AM' },
      { text: 'What about a gamified sustainability tracker?', sender: 'them', time: '10:33 AM' },
      { text: 'Love it! I can handle the UI/UX. Let me sketch some wireframes.', sender: 'me', time: '10:35 AM' },
      { text: 'Perfect. I\'ll start on the backend API.', sender: 'them', time: '10:36 AM' },
    ],
    timestamp: '1 day ago',
    status: 'accepted',
  },
  {
    id: 4,
    type: 'chat',
    from: USERS[14],
    messages: [
      { text: 'Hi! Saw your profile - great ML skills!', sender: 'them', time: '9:00 AM' },
      { text: 'Thanks! What are you working on?', sender: 'me', time: '9:05 AM' },
      { text: 'Building a GraphQL API for a fintech project. Need help with the ML component.', sender: 'them', time: '9:07 AM' },
    ],
    timestamp: '2 days ago',
    status: 'accepted',
  },
];

const NOTIFICATIONS = [
  { id: 1, type: 'connection', text: 'Marcus Chen wants to team up with you', time: '2 hours ago', unread: true, userId: 2 },
  { id: 2, type: 'message', text: 'New message from Sofia Rodriguez', time: '5 hours ago', unread: true, userId: 3 },
  { id: 3, type: 'team', text: 'You were invited to join "MindBridge" team', time: '1 day ago', unread: true, userId: null },
  { id: 4, type: 'hackathon', text: 'HackAI 2026 starts in 3 weeks!', time: '1 day ago', unread: false, userId: null },
  { id: 5, type: 'connection', text: 'James Okonkwo wants to team up with you', time: '2 days ago', unread: false, userId: 4 },
  { id: 6, type: 'hackathon', text: 'ETHGlobal Brussels registration closing soon', time: '3 days ago', unread: false, userId: null },
  { id: 7, type: 'endorsement', text: 'Sofia Rodriguez endorsed your React skills', time: '4 days ago', unread: false, userId: 3 },
];

const ENDORSEMENTS = [
  { skill: 'React', from: USERS[2], comment: 'Amazing frontend work on EcoQuest!' },
  { skill: 'TypeScript', from: USERS[14], comment: 'Clean, well-typed code throughout.' },
  { skill: 'Node.js', from: USERS[1], comment: 'Built a solid API in record time.' },
  { skill: 'UI/UX', from: USERS[11], comment: 'Great eye for detail and user flows.' },
];

// Current logged-in user
const CURRENT_USER = USERS[0]; // Aisha Patel

// Utility: get skill tag color class
function getSkillColorClass(skillName) {
  const skill = SKILL_TAGS.find(s => s.name === skillName);
  return skill ? `tag-${skill.color}` : 'tag-blue';
}
